### ISSUE TITLE
Usable?

### ISSUE THREAD

**Issue by PanMan** [Dolphiq/craft3-plugin-sitemap#1]
Hi!
I understand this is still a work in progress, but is it usable? If not, can I help?
Fixing a sitemap for our craft3 site is on my todo... Thnx!

**Comment by johanzandstra** [comment]
@PanMan Thanks for your message. We are working on this plugin right now! keep you posted

**Comment by johanzandstra** [comment]
We released the first version today. Please let me know if there are issues with the plugin.

**Comment by johanzandstra** [comment]
@PanMan It's just approved in the craft plugin store. Now it's more easy to install it from the CP

**Comment by PanMan** [comment]
Cool, just deployed it! (we're not using the plugin store, as we have multi server hosting, and I'm fairly sure that won't work).
