### ISSUE TITLE
Make multi-site compatible

### ISSUE THREAD

**Issue by timkelty** [Dolphiq/craft3-plugin-sitemap#10]
The current implementation is not multi-site compatible.

You are using `$app->config->general->siteUrl`, which in a multisite, can be an array.

Ideally, I think you'd want to structure things so you're actually dealing with `craft\elements\Element`, so you can just use `craft\base\Element::getUrl()`. That you don't have to monkey around with building the url yourself, making exceptions for `__home__`, among other things.

If not that, it would at least be better to use `craft\helpers\UrlHelper::url($item['uri'])`, rather than getting the raw config var, so this would work for multi-sites.

**Comment by nikolowry** [comment]
@timkelty https://github.com/Dolphiq/craft3-plugin-sitemap/pull/11

**Comment by johanzandstra** [comment]
thanks your your feedback @timkelty  and @nikolowry !
