### ISSUE TITLE
Mulltilingual sites support?

### ISSUE THREAD

**Issue by MiMaMuh** [Dolphiq/craft3-plugin-sitemap#14]
Hi,

is there an idea how to support multilingual sites?

For example google [suggest](https://support.google.com/webmasters/answer/2620865?hl=en) to treat them within the sitemap.xml like so per site (for example `en` as default and `de` as second language): 
```
<url>
    <loc>http://www.example.com/english/</loc>
    <xhtml:link 
                 rel="alternate"
                 hreflang="de"
                 href="http://www.example.com/deutsch/"
                 />
</url>
```

Right now the plugin will generate it like so:
```
<url>
    <loc>http://www.example.com/english/</loc>
</url>
<url>
    <loc>http://www.example.com/deutsch/</loc>
</url>
```

Is there any support for multilingual setups planned or possible right now?

**Comment by johanzandstra** [comment]
@MiMaMuh, sounds interesting! What about the compatibility with other search engines? Do you have any experience with that?

**Comment by johanzandstra** [comment]
@MiMaMuh we just added support for this in the last release, thanks!
