### ISSUE TITLE
Settings page redirecting to a 404 Template

### ISSUE THREAD

**Issue by adampatpattison** [Dolphiq/craft3-plugin-sitemap#15]
When looking at the settings I am being redirected from
`/admin/settings/plugins/sitemap` to `/admin/settings/sitemap` which is not available.

![image](https://user-images.githubusercontent.com/4398922/36475892-1c96adf0-16f4-11e8-86f9-fd7e2a040f32.png)

I am assuming this is something in my setup but I honestly can't think what?!? Any chance you could shed any light on this. 

Apologies if this is not the correct way to reach out to you.

**Comment by ddbr** [comment]
Same Problem here and in the redirect Dolphiq/craft3-plugin-redirect plugin aswell.

**Comment by johanzandstra** [comment]
@adampatpattison, @ddbr just fixed it in release v1.0.8 thanks!
