### ISSUE TITLE
Plugin settings page in the backend throws database exception

### ISSUE THREAD

**Issue by azazelA** [Dolphiq/craft3-plugin-sitemap#19]
Hi, I installed this plugin using composer on my Craft CMS 3.0.3.1, when heading to mysite.com/admin/settings/sitemap I'm presented with a database exception seen in the image attached below:
<img width="1604" alt="screen shot 2018-04-18 at 11 39 46 pm" src="https://user-images.githubusercontent.com/19649989/38951370-e0864c72-4361-11e8-9181-545666f04a07.png">
Would you please verify if It's an issue with my craft installation?

**Comment by aliPunch** [comment]
same here

**Comment by levinelson** [comment]
Same here, after a fresh Craft 2 to 3 upgrade

**Comment by johanzandstra** [comment]
Should be fixed in next release
