### ISSUE TITLE
Sitemap error

### ISSUE THREAD

**Issue by pellens** [Dolphiq/craft3-plugin-sitemap#27]
When visiting www.mysite.com/sitemap.xml, I receive the following error:

This page contains the following errors:
error on line 3 at column 6: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.

So there are 2 whitespaces/lines before the sitemap is shown...
<img width="438" alt="screen shot 2018-10-26 at 14 06 56" src="https://user-images.githubusercontent.com/198456/47565340-6b7be100-d928-11e8-8d0c-deca6829f77a.png">

Any idea on how to fix this?

**Comment by epapada** [comment]
Same issue here. Have you found a way around it?

**Comment by johanzandstra** [comment]
Please let me know if there is something in de (debug) log file.
