### ISSUE TITLE
Database Error when installing plugin

### ISSUE THREAD

**Issue by wineworkskeith** [Dolphiq/craft3-plugin-sitemap#28]
After installing the plugin and going to the plugin's settings page I get this:

![screen shot 2019-03-04 at 12 31 26 pm](https://user-images.githubusercontent.com/37811778/53761132-a44d3900-3e79-11e9-9812-92a0eb8bbb08.png)

Here is my install info:

![screen shot 2019-03-04 at 12 32 41 pm](https://user-images.githubusercontent.com/37811778/53761145-aca57400-3e79-11e9-837c-602bb4e515ea.png)

**Comment by ellalderton** [comment]
I had the same, uninstalled, removed then reinstalled and it worked.
