### ISSUE TITLE
Plugin displays deleted sections

### ISSUE THREAD

**Issue by petehjfd** [Dolphiq/craft3-plugin-sitemap#32]
The Sitemap settings page displays sections that have been deleted.  I'm guessing it should be excluding sections where `dateDeleted` is not `NULL` in the database.

**Comment by petehjfd** [comment]
Further to this, we have found that the sitemap on the frontend is displaying deleted entries. Could it be that the plugin has not been updated to work with Craft's new soft deletes?

**Comment by Anubarak** [comment]
@petehjfd The plugin wasn't updated for over a year so yes, it doesn't include project config, nor soft deletion.
You could use my fork or wait for the developer to merge my pull request to have these features

**Comment by petehjfd** [comment]
Oh perfect, thanks @Anubarak
