### ISSUE TITLE
Craft 3.2 compatibility issues

### ISSUE THREAD

**Issue by christianruhstaller** [Dolphiq/craft3-plugin-sitemap#34]
Currently this plugin does not work anymore in a Craft 3.2 installation because of the added soft deletes and new drafting and versioning feature in Craft.

The custom built SQL queries would need to have added where checks for the element joins.
But besides that, it seems this plugin is not maintained anymore.

I just want this to stand here for others to see. :)

**Comment by fathomali** [comment]
+1 on this, just commenting so Dolphiq sees this!

It's counting every revision as an entry, so i have about 50 homepages in my sitemap (for example).

**Comment by johanzandstra** [comment]
@christianruhstaller Thanks, will look into this!

**Comment by darylknight** [comment]
Yeah it looks like if I enable one single, it's adding that entry multiple times to the sitemap - presumably for all the different entry versions

**Comment by elfacht** [comment]
Yep, just stumbled upon it as well. It's incrementing with every save and setting change.

![Screenshot 2019-09-10 um 17 14 08](https://user-images.githubusercontent.com/529443/64626637-6e6fab00-d3ee-11e9-8f06-fef6f6ab5ad8.jpg)

**Comment by sibren1** [comment]
In multisite the sitemap.xml is showing error:

![2019-09-130749](https://user-images.githubusercontent.com/25082497/64869129-05cc3c80-d641-11e9-9de6-89d4b437f1ec.jpg)

**Comment by harispepic** [comment]
@johanzandstra any news on this issue?

**Comment by johanzandstra** [comment]
The plugin should be compatible with Craft 3.2+ With the latest changes

**Comment by solutiondrop** [comment]
I have two project that are both updated to 1.2 and Craft 3.3.19 and the sitemap.xml is still showing multiple different entry versions for singles -- with the lastmod date being the only difference. Thanks.
