### ISSUE TITLE
Sitemap showing temp URLS?

### ISSUE THREAD

**Issue by kevadamson** [Dolphiq/craft3-plugin-sitemap#40]
Getting URLs like this showing in the sitemap: /__temp_gLouMRSa9uMX3szi8Orcsal1jmpoaP2uVnyt

**Comment by brandonkelly** [comment]
@johanzandstra Let me know if I can help you look into this.

**Comment by ruthshepperd** [comment]
Getting this issue too. If this can be fixed, that would be great.

**Comment by brandonkelly** [comment]
I suspect this will be fixed in Craft 3.4 per craftcms/cms@c467fa73c105aecac1356d5b1f225f530b57aba7.

**Comment by ambidustrious** [comment]
This still seems to be an issue as of 3.4.10.1

**Comment by howells** [comment]
Same issue on 3.4.15 - would love to get this working, it's the only sitemap generator that seems to work well for me

**Comment by Friksel** [comment]
> Same issue on 3.4.15 - would love to get this working, it's the only sitemap generator that seems to work well for me

Confirmed. Same here (seen on a Channel section).

**Comment by zzseba78** [comment]
Same issue here:
Output .../product/__temp_mNO9jnHPGrHCN2sgfdKTjc6odE6BVVxYWH5b`

**Comment by ambidustrious** [comment]
Yes. And now I’ve noticed that it’s showing inactive posts as well

**Comment by johanzandstra** [comment]
Sorry for the long delay, this is fixed in the last version v1.3.0
