### ISSUE TITLE
Sitemap showing deleted entries

### ISSUE THREAD

**Issue by nathan-pbd** [Dolphiq/craft3-plugin-sitemap#41]
I have vacancy entries that are only live for so many weeks, but even when removed they are still showing in the sitemap and causing crawl errors with Google Search Console.

Is there a way to reset the sitemap XML when this happens? I already have the change frequency set to daily

Thank you!

**Comment by robinvdvleuten** [comment]
I have the same issue! Also already deleted sections show up in the configuration panel of the plugin.

**Comment by johanzandstra** [comment]
Sorry for the long delay, this is fixed in the last version v1.3.0
