### ISSUE TITLE
Future post dates not honored

### ISSUE THREAD

**Issue by mikestreety** [Dolphiq/craft3-plugin-sitemap#47]
Hi, thanks for a great plugin - it's the first thing I install on my sites.

One thing I noticed on my most recent venture is that posts that appear in the future appear in the sitemap.

I have set up and scheduled several posts to go live over the next few weeks by using the post date and they all appear in the sitemap.

Thanks again

**Comment by johanzandstra** [comment]
Sorry for the long delay, this is fixed in the last version v1.3.0
